# Gulp will reference these paths when it copies files
PATHS:
  html:
    - "./*.html"
    - "./**/*.html"
  images:
    - "src/img/**/*"
  sass:
#    foundation:
#      - "node_modules/foundation-sites/scss"
  javascript:
    vendors:
#      - "node_modules/jquery/dist/jquery.min.js"
#      - "node_modules/what-input/dist/what-input.min.js"
#      - "node_modules/foundation-sites/dist/js/foundation.min.js"
#    fontawesome:
#      - "node_modules/@fortawesome/fontawesome-free/js/all.js"
    custom:
      - "src/js/**/_*.js"
